spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/members/**, /settings/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        - id: live-lecture-service
          uri: lb://live-lecture-service
          predicates:
            - Path=/musics/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: live-lecture-service
                fallbackUri: forward:/fallback/live-lecture
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        - id: recorded-lecture-service
          uri: lb://recorded-lecture-service
          predicates:
            - Path=/recommend/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: recorded-lecture-service
                fallbackUri: forward:/fallback/recorded-lecture
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        - id: signaling-service
          uri: lb://signaling-service
          predicates:
            - Path=/signaling/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: signaling-service
                fallbackUri: forward:/fallback/signaling
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.client.service-url.credentials}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  file:
    name: /var/log/gateway/gateway.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
    enabled-by-default: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        minimumNumberOfCalls: 50
        waitDurationInOpenState: 60s
        failureRateThreshold: 50

