spring:
  cloud:
    gateway:
      routes:
        - id: user-service-routes
          uri: lb://user-service
          predicates:
            - Path=/user/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/user/fallback
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        - id: live-lecture-service-routes
          uri: lb://lecture-service
          predicates:
            - Path=/live-lecture/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: live-lecture-service
                fallbackUri: forward:/fallback/live-lecture
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        - id: recorded-lecture-service-routes
          uri: lb://lecture-service
          predicates:
            - Path=/recorded-lecture/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: recorded-lecture-service
                fallbackUri: forward:/fallback/recorded-lecture
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        - id: lecture-service-routes
          uri: lb://lecture-service
          predicates:
            - Path=/lecture/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: lecture-service
                fallbackUri: forward:/fallback/lecture
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.client.service-url.credentials}@localhost:8761/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"