jwt:
  secret: eJGiXACTWKhH2kN7RkwCZnqhMTPTI0ch
#  access-token-expiration: 3600000  # 1시간
#  refresh-token-expiration: 604800000  # 7일
  access-token-expiration: 3000  # 1시간
  refresh-token-expiration: 604800000  # 7일